export type UIStrings = {
  heroKicker: string;
  heroTitle: string;
  heroSubtitle: string;
  sopSections: string;
  passMark: string;
  warehouses: string;
  stepDetails: string;
  stepSop: string;
  stepQuiz: string;
  stepResult: string;
  detailsTitle: string;
  detailsSubtitle: string;
  packerName: string;
  employeeCode: string;
  warehouse: string;
  selectWarehouse: string;
  shift: string;
  firstShift: string;
  secondShift: string;
  nightShift: string;
  language: string;
  startTraining: string;
  readSopStart: string;
  back: string;
  answered: string;
  of: string;
  answerAll: string;
  submit: string;
  submitting: string;
  passed: string;
  failed: string;
  correctCount: string;
  correctAnswer: string;
  tryAgain: string;
  attemptsLeft: string;
  noAttemptsLeft: string;
  flaggedNotice: string;
  attemptLabel: string;
  checkingAttempts: string;
  newPacker: string;
  saveError: string;
  perfectRequired: string;
};

export type TrainingContent = {
  label: string;
  ui: UIStrings;
  sop: { title: string; points: string[] }[];
  questions: { q: string; options: string[] }[];
};
